<?php

namespace Bytes\CommandBundle\Tests\Command;

use Bytes\CommandBundle\Command\Traits\CounterTableHelperTrait;
use Bytes\CommandBundle\Tests\fixtures\Command\SampleCounterCommand;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Tester\CommandTester;

/**
 *
 */
class SampleCounterCommandTest extends TestCase
{
    use CounterTableHelperTrait;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     *
     */
    public function testSampleSuccessOnlyCommandExecute()
    {
        $command = new SampleCounterCommand('app:sample');
        $command->setName('app:sample');
        $tester = new CommandTester($command);

        $tester->execute([]);
        $this->assertEquals(Command::SUCCESS, $tester->getStatusCode());
    }
}